# Generated by Django 4.2.4 on 2023-08-18 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('answer_text', models.CharField(max_length=400)),
                ('part_of_speech', models.CharField(blank=True, choices=[('N', 'Noun'), ('V', 'Verb'), ('Adj', 'Adjective'), ('Adv', 'Adverb'), ('Con', 'Conjunction'), ('PhV', 'Phrasal Verb'), ('O', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyms', models.JSONField(blank=True, null=True)),
                ('usage_example', models.CharField(blank=True, max_length=400, null=True)),
                ('note', models.CharField(blank=True, max_length=400, null=True)),
                ('flashCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flashcard')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
    ]
