# Generated by Django 4.2.4 on 2023-08-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='flashCard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.flashcard'),
        ),
    ]
